Dokujunkies_Geschichtepolitik:
    feed: "http://dokujunkies.org/dokus/geschichtepolitik/moderne-geschichtepolitik-dokus/feed"
    blacklist:
      - Papst
      - Mittelalter
    quality: 720p
    downloadfolder: /share/Web/temp/Dokus
    hoster: uploaded
RMZ_Shows:
    feed: "http://rmz.cr/feed"
    shows:
      - Wilderness Vet
      - The Voyager with Josh Garcia
      - Chicago Fire
    quality: 720p
    downloadfolder: /share/Web/temp/TV-Shows
CRE:
    feed: "http://cre.fm/feed/m4a/"
    downloadfolder: /share/Web/temp/Audio/cre

